iter13
dlomanov/mon pull request #13
Opened 2024-01-22 20:08 UTC by dlomanov

# Инкремент 13

## Задание для трека «Сервис сбора метрик и алертинга»

Измените весь свой код в соответствии со знаниями, полученными в этой теме. Добавьте обработку retriable-ошибок.

Retriable-ошибки — это ошибки, которые могут быть исправлены повторной попыткой выполнения операции.
Это бывает полезно для программ, которые работают с сетью или файловой системой, где возможны временные проблемы связи или доступа к данным.
Ошибки могут быть вызваны различными причинами, такими как перегрузка сервера, недоступность сети или ошибки в коде программы.

Примеры retriable-ошибок:

- Ошибка связи с сервером при отправке запроса.
- Ошибка чтения данных из сети или БД из-за проблем соединения.
- Ошибка доступа к файлу, который был заблокирован другим процессом.

Сценарии возможных ошибок:

- Агент не сумел с первой попытки выгрузить данные на сервер из-за временной невозможности установить соединение с сервером.
- При обращении к PostgreSQL cервер получил ошибку транспорта (из категории Class 08 — Connection Exception).

Стратегия реализации:

- Количество повторов должно быть ограничено тремя дополнительными попытками.
- Интервалы между повторами должны увеличиваться: 1s, 3s, 5s.
- Чтобы определить тип ошибки PostgreSQL, с которой завершился запрос, можно воспользоваться библиотекой `github.com/jackc/pgerrcode`, в частности `pgerrcode.UniqueViolation`.

2024-01-26 16:52 UTC, bambruysk requested changes
Лучше сделать сохранения в базу при каждом обращении, а не дампить в нее как в случае с файлами, так как дальше мы будем развивать итменно этот момент. Поэтому делаем проще запрос -обработали - сохранили. Аналогично получение тоже должно быть сразу из базы

2024-01-26 16:52 UTC, bambruysk commented on internal/apps/server/handlers/update.go
> +func UpdateByJSON(logger *zap.Logger, db interfaces.Storage) http.HandlerFunc {
чтобы не прокидывать эти логгер и бд все время везде через аргументы можно сделать хендлеры методами структуры

2024-01-26 16:52 UTC, bambruysk commented on internal/storage/internal/dumper/db.go
> +	mu          sync.Mutex
мьютекс не нужен pgx и постгрес сам разрулит вопросы конкурентности

2024-01-26 16:52 UTC, bambruysk commented on internal/storage/internal/dumper/db.go
> +	source mem.Storage,
это тоже может быть методом БД

2024-01-26 16:52 UTC, bambruysk commented on internal/storage/internal/dumper/noop.go
> +}
лучше не использовать init функции

2024-01-28 14:58 UTC, dlomanov commented on internal/apps/server/handlers/update.go
> +func UpdateByJSON(logger *zap.Logger, db interfaces.Storage) http.HandlerFunc {
Сделал методами структуры с зависимостями

2024-01-28 14:58 UTC, dlomanov commented on internal/storage/internal/dumper/db.go
> +	mu          sync.Mutex
Удалил DBDumper, в реализации PGStorage не использую мьютексы

2024-01-28 14:58 UTC, dlomanov commented on internal/storage/internal/dumper/db.go
> +	source mem.Storage,
Зарефакторил код. Теперь есть 3 хранилища (in-memory-, file- и pg-). Dumper используется только в FileStorage, остальные удалил

2024-01-28 14:58 UTC, dlomanov commented on internal/storage/internal/dumper/noop.go
> +}
Убрал init-функции в коде, написал вопрос "почему" в пачку

2024-01-28 15:04 UTC, dlomanov commented on internal/storage/internal/dumper/db.go
> +	source mem.Storage,
Вместе с рефакторингом пропал написанный retry. Но не вижу особого смысла его вручную реализовывать. В PGStorage используется методы sqlx, которые поддерживают retry

2024-01-29 18:44 UTC, bambruysk approved these changes
Принято

2024-01-29 18:44 UTC, bambruysk commented on internal/storage/internal/dumper/db.go
> +	source mem.Storage,
ну и правильно)

2024-01-30 06:32 UTC, merged