Iter5
dlomanov/mon pull request #5
Opened 2023-12-13 08:28 UTC by dlomanov

# Инкремент 5

## Задание по треку «Сервис сбора метрик и алертинга»

Доработайте агент, чтобы он мог изменять свои параметры запуска по умолчанию через переменные окружения:

- `ADDRESS` отвечает за адрес эндпоинта HTTP-сервера.
- `REPORT_INTERVAL` позволяет переопределять `reportInterval`.
- `POLL_INTERVAL` позволяет переопределять `pollInterval`.

Значения интервалов времени должны задаваться в секундах.

Доработайте сервер, чтобы он мог изменять свои параметры запуска по умолчанию через переменные окружения:

- `ADDRESS` отвечает за адрес эндпоинта HTTP-сервера.

Приоритет параметров должен быть таким:

- Если указана переменная окружения, то используется она.
- Если нет переменной окружения, но есть аргумент командной строки (флаг), то используется он.
- Если нет ни переменной окружения, ни флага, то используется значение по умолчанию.

2023-12-14 16:44 UTC, bambruysk requested changes
Круто 
Надо чуть доработать по замечаниям 
Naked return - во многих местах считается антипаттерном - ( есть даже стандартный линтер который его проверяет) 
Лучше бы по возможности его избегать

2023-12-14 16:44 UTC, bambruysk commented on cmd/agent/config.go
> +}
почти такого же результата можно достичь используя 
fmt.Sprintf("$#v", c) или fmt.Sprintf("$+v", c) - попробуйте

2023-12-14 16:44 UTC, bambruysk commented on cmd/agent/main.go
> +	err := agent.Run(cfg.Addr, cfg.PollInterval, cfg.ReportInterval)
луячше бы агенту принмать конфиг целиком, а то потом количество параметров будет расти и не нужно будет переписывать это место

Сделать конфиг экспорируемой структурой - нормально)

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/agent/collector/collector.go
> +	client := resty.New()
клиент можно слелать полем коллектора и не создвать каждый раз заново и BaseURL ему выставить

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/agent/collector/collector.go
> +		if err == nil {
обычно мы проверяем на err != nil - это более идиоматично

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/agent/collector/collector.go
> +		if err == nil {
То есть в начале проверяем на некорректные случаи - потом корректный в конце

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/agent/collector/collector.go
> +}
Если это просто обертка для вывода логов - то лучше назвать ее LogUpdated() - чтобы сразу было понятно что она не связана с логикой приложения

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/agent/agent.go
> +	for i := 0; i < math.MaxInt64; i++ {
вроде бы ш внутри цикла не исепользуется -  можно просто for

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/binding/metric.go
> +	ErrInvalidMetricPath     apperrors.Code = "ERR_VALIDATION_INVALID_METRIC_PATH"
согласно гошным сталйгайдам тест ошибки пишется маленькими буквами через пробелы

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/binding/metric.go
> +		return
лучше бы  просто return metric, ErrInvalidMetricType.New("unknown metric type %s", raw.Type)

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/binding/metric.go
> +	return
У гошных ошибок есть еще замечательная функция как обертывание (wrapping) - для кастомных типов ошибок ее тоже можно поддержать

мне кажется она бы тут пригодилась 

получилось бы что-то типа 

metric, err := createMetric(metricType, raw.Name, raw.Value)
if err != nil {
	return metric, fmt.Errorf("invalid value type for %s metric: %w", metricType, err)
}
return metric, nil

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/binding/metric.go
> +	return
более принят такой стиль
```

	switch metricType {
	case metrics.MetricGauge:
		return  gauge.NewMetric(metricName, metricValue)
	case metrics.MetricCounter:
		return  counter.NewMetric(metricName, metricValue)
	default:
		return metric, ErrUnsupportedMetricType.New("unsupported %s metric")
	}
}


```

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/get.go
> +		}
ЗДесь больше на BadRequest похоже

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/get.go
> +
статус лучше явно указать

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/get.go
> +func Get(db storage.Storage) http.HandlerFunc {
Этот интерфейс лучше обхявить тут - чем экспортировать из вне

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/report.go
> +		t := template.Must(template.New("report").Parse(htmlTemplate))
шаблон лучше спарсить один раз, а не прик каждом запросе

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/report.go
> +		_ = t.Execute(w, result)
ошибка игнорится? Нехорошо

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/update.go
> +			w.WriteHeader(statusCode(apperr))
А почему бы не научить AppError возвращать код самостоятельно?
сделать ей метод HTTPStatus() ?

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/update.go
> +		err = nil
лишнее - она и так nil иначе вышли бы уже

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/handlers/update.go
> +		if err == nil {
Лучше if err != nil {

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/server_test.go
> +) (resp *http.Response, body string) {
чтобы вывод тестов работал более точно лучше помечать такие функции через t.Helper() https://pkg.go.dev/testing#T.Helper

2023-12-14 16:44 UTC, bambruysk commented on internal/apps/server/server.go
> +	db := storage.NewStorage()
Хранилище лучше передавать сюда через аргумент интерфейсного типа из вне
Сейчас оно у вас простое - в памяти все и тесты нормально работают - если же это была бы реальная БД - то такие тесты не запустились бы

В тестах же можно создать моковое хранлище с тем же интерфейсаом и использовать его

2023-12-14 16:44 UTC, bambruysk commented on internal/entities/metrics/counter/counter_metric.go
> +	value, err := strconv.ParseInt(valueString, 10, 64)
ошибку лучше проверять на nil тоже и сразу - линтеры не пустят)

2023-12-14 16:44 UTC, bambruysk commented on internal/entities/metrics/metric_type.go
> +}
немного излишне - fmt сам догадается что это строка

2023-12-14 16:44 UTC, bambruysk commented on internal/storage/memstorage.go
> +	storage map[string]string
лучше защитить доступ к мапе из разных потоков через mutex

2023-12-15 10:25 UTC, dlomanov commented on cmd/agent/config.go
> +}
Удалил метод `String()` -- вместо него `%+v`

2023-12-15 10:25 UTC, dlomanov commented on cmd/agent/main.go
> +	err := agent.Run(cfg.Addr, cfg.PollInterval, cfg.ReportInterval)
Сделал конфиг экспортируемой структурой пакета `agent`

2023-12-15 10:30 UTC, dlomanov commented on internal/apps/agent/collector/collector.go
> +	client := resty.New()
Сделал `client` полем структуры `Collector`. Инициализация происходит в методе `NewCollector`

2023-12-15 10:30 UTC, dlomanov commented on internal/apps/agent/collector/collector.go
> +		if err == nil {
Переделал условние на `err != nil`

2023-12-15 10:30 UTC, dlomanov commented on internal/apps/agent/collector/collector.go
> +}
Переименовал метод `Updated` в `LogUpdated`

2023-12-15 10:31 UTC, dlomanov commented on internal/apps/server/server_test.go
> +) (resp *http.Response, body string) {
Добавил в функцию вызов `t.Helper()`

2023-12-15 10:31 UTC, dlomanov commented on internal/apps/server/server.go
> +	db := storage.NewStorage()
Добавил аргумент интерфейсного типа `storage.Storage`.
Переделал `server_test.go` на использование мока для хранилища.
Мок расположил рядом в пакете `mocks`

2023-12-15 10:31 UTC, dlomanov commented on internal/entities/metrics/counter/counter_metric.go
> +	value, err := strconv.ParseInt(valueString, 10, 64)
Добавил проверку `err != nil` с ранним выходом здесь и в `gauge_metric.go`

2023-12-15 10:31 UTC, dlomanov commented on internal/entities/metrics/metric_type.go
> +}
Удалил метод

2023-12-15 10:32 UTC, dlomanov commented on internal/storage/memstorage.go
> +	storage map[string]string
Добавил `sync.Mutex` в качестве поля `memStorage`, добавил `lock/unlock` в методы `memStorage`

2023-12-18 12:16 UTC, bambruysk approved these changes
Принято, но некоторые замечания не поправлены (игнор ошибок etc) 

лучше поправить

2023-12-18 16:18 UTC, merged