iter9
dlomanov/mon pull request #9
Opened 2024-01-11 17:48 UTC by dlomanov

# Инкремент 9
## Задание по треку «Сервис сбора метрик и алертинга»

Доработайте код сервера, чтобы он мог с заданной периодичностью сохранять текущие значения метрик на диск в указанный файл, а на старте — опционально загружать сохранённые ранее значения. При штатном завершении сервера все накопленные данные должны сохраняться.

Сервер должен принимать соответствующие параметры конфигурации через флаги и переменные окружения:

- Флаг `-i`, переменная окружения `STORE_INTERVAL` — интервал времени в секундах, по истечении которого текущие показания сервера сохраняются на диск (по умолчанию 300 секунд, значение `0` делает запись синхронной).
- Флаг `-f`, переменная окружения `FILE_STORAGE_PATH` — полное имя файла, куда сохраняются текущие значения (по умолчанию `/tmp/metrics-db.json`, пустое значение отключает функцию записи на диск).
- Флаг `-r`, переменная окружения `RESTORE` — булево значение (`true/false`), определяющее, загружать или нет ранее сохранённые значения из указанного файла при старте сервера (по умолчанию `true`).

Приоритет параметров сервера должен быть таким:

- Если указана переменная окружения, то используется она.
- Если нет переменной окружения, но есть флаг, то используется он.
- Если нет ни переменной окружения, ни флага, то используется значение по умолчанию.

2024-01-14 12:12 UTC, bambruysk requested changes
Очень хорошо, но нужно чуть доработаьт в части gracefulShutdown

2024-01-14 12:12 UTC, bambruysk commented on internal/apps/apimodels/mapping.go
> +	}
проще использовать switch в таких случаях 

например здесь выглядело бы вот так

```   
       switch {
	case key.Type == entities.MetricGauge && model.Value != nil:
		return model.Value, nil
	case key.Type == entities.MetricCounter && model.Delta != nil:
		return model.Delta, nil
	default:
		return  entity, ErrInvalidMetricValue.Newf("invalid value for metrics type %s", key.Type)
      }
```

2024-01-14 12:12 UTC, bambruysk commented on internal/apps/apimodels/mapping.go
> +		err = ErrInvalidMetricType.Newf("unknown entity type %s", key.Type)
можно в одну строчку return - так нагляднее

2024-01-14 12:12 UTC, bambruysk commented on internal/apps/server/handlers/bind/metrics.go
> +			err = errors.Join(ErrInvalidMetricValue.New(), err)
здесь лучше добавить return и избавиться от else. Ну и switch

2024-01-14 12:12 UTC, bambruysk commented on internal/storage/memstorage.go
> +	}
сюда бы добавить graceful завершение этого цикла -  в случае завершения выолпоения программы, сброс остатков на диск и выход. Можно сделать через контекст например, или канал

2024-01-15 20:56 UTC, dlomanov commented on internal/apps/server/handlers/bind/metrics.go
> +			err = errors.Join(ErrInvalidMetricValue.New(), err)
Переделал на switch, добавил return-ы

2024-01-15 20:56 UTC, dlomanov commented on internal/apps/apimodels/mapping.go
> +		err = ErrInvalidMetricType.Newf("unknown entity type %s", key.Type)
Переделал return в одну строчку

2024-01-15 20:56 UTC, dlomanov commented on internal/apps/apimodels/mapping.go
> +	}
Переделал на switch

2024-01-15 20:57 UTC, dlomanov commented on internal/storage/memstorage.go
> +	}
Добавил graceful shutdown через контекст. Последний дамп решил не добавлять, так как у меня это реализовано через метод `Close()`.

`Close()` будет вызван как при `STORE_INTERVAL == 0` (`dumpLoop` не дойдет до `for`), так и при `STORE_INTERVAL != 0`

2024-01-17 15:54 UTC, bambruysk approved these changes
Принято

2024-01-18 15:20 UTC, merged